// placesData.js
const places = [
  {
    id: 1,
    title: 'Knee Deep in Sound',
    description: 'Hot Since 82, Chris Stussy, Toman',
    date: '05 OCT',
    location: 'Punta Carrasco',
    image:
      'https://images.pexels.com/photos/7715514/pexels-photo-7715514.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 2,
    title: 'Mutek BA',
    description: 'Inda Jani',
    date: '05 OCT',
    location: 'Crobar',
    image: 'https://source.unsplash.com/600x400/?dj-set',
  },
  {
    id: 3,
    title: 'Pacha Buenos Aires',
    description: 'John Digweed, Hernán Cattáneo',
    date: '12 OCT',
    location: 'Costanera Norte',
    image: 'https://source.unsplash.com/600x400/?party',
  },
  {
    id: 4,
    title: 'Input Buenos Aires',
    description: 'DJ Tennis, Tale Of Us',
    date: '18 OCT',
    location: 'Palermo',
    image: 'https://source.unsplash.com/600x400/?concert',
  },
  {
    id: 5,
    title: 'Club Bahrein',
    description: 'Maceo Plex, Seth Troxler',
    date: '22 OCT',
    location: 'Microcentro',
    image: 'https://source.unsplash.com/600x400/?crowd',
  },
  {
    id: 6,
    title: 'Rose in Rio',
    description: 'Solomun, Adriatique',
    date: '28 OCT',
    location: 'Costanera Norte',
    image: 'https://source.unsplash.com/600x400/?nightlife',
  },
  {
    id: 7,
    title: 'Jet Lounge',
    description: 'Peggy Gou, Amelie Lens',
    date: '02 NOV',
    location: 'Costanera Norte',
    image: 'https://source.unsplash.com/600x400/?club',
  },
  {
    id: 8,
    title: 'The Bow',
    description: 'Charlotte de Witte, Carl Cox',
    date: '09 NOV',
    location: 'Puerto Madero',
    image: 'https://source.unsplash.com/600x400/?music-event',
  },
  {
    id: 9,
    title: 'Palermo Groove',
    description: 'DJ Koze, Black Coffee',
    date: '15 NOV',
    location: 'Palermo',
    image: 'https://source.unsplash.com/600x400/?dance-floor',
  },
  {
    id: 10,
    title: 'Cocoliche Club',
    description: 'Len Faki, Nina Kraviz',
    date: '21 NOV',
    location: 'San Telmo',
    image: 'https://source.unsplash.com/600x400/?techno',
  },
  {
    id: 11,
    title: 'Niceto Club',
    description: 'Matador, Patrice Bäumel',
    date: '30 NOV',
    location: 'Palermo',
    image: 'https://source.unsplash.com/600x400/?live-performance',
  },
  {
    id: 12,
    title: 'Funk Club',
    description: 'Ellen Allien, Boris Brejcha',
    date: '05 DEC',
    location: 'Recoleta',
    image: 'https://source.unsplash.com/600x400/?dj',
  },
  {
    id: 13,
    title: 'Lost Buenos Aires',
    description: 'Richie Hawtin, Adam Beyer',
    date: '12 DEC',
    location: 'Villa Urquiza',
    image: 'https://source.unsplash.com/600x400/?music-festival',
  },
  {
    id: 14,
    title: 'Crobar Buenos Aires',
    description: 'Jamie Jones, Loco Dice',
    date: '20 DEC',
    location: 'Palermo',
    image: 'https://source.unsplash.com/600x400/?event',
  },
  {
    id: 15,
    title: 'Requiem Club',
    description: 'Dubfire, Sasha',
    date: '27 DEC',
    location: 'Almagro',
    image: 'https://source.unsplash.com/600x400/?night-scene',
  },
];

export default places;
